version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - setup_remote_docker
      - run:
          name: Docker compose
          command: docker-compose -f docker/docker-compose.yml start
