version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - setup_remote_docker
      - run:
          name: Build docker
          command: docker build -f docker/Dockerfile docker/ -t playground
      - run:
          name: Run built docker
          command: docker run playground
